// _app.tsx
import type { AppProps } from "next/app";
import { AuroraTestnet } from "@thirdweb-dev/chains";
import { ThirdwebProvider } from "@thirdweb-dev/react";
// import HeaderNav from "@/src/components/HeaderNav";
// import Footer from "../components/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
// Mintbase
import { MintbaseWalletContextProvider } from "@mintbase-js/react";
import { QueryClient, QueryClientProvider } from "react-query";
const MintbaseWalletSetup = {
  contractAddress: "hellovirtualworld.mintspace2.testnet",
  network: "testnet",
  callbackUrl: "http://localhost:3000",
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const activeChain = "aurora";

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThirdwebProvider
      activeChain={AuroraTestnet}
      clientId={process.env.NEXT_PUBLIC_CLIENT_ID}
    >
      <QueryClientProvider client={queryClient}>
        <MintbaseWalletContextProvider {...MintbaseWalletSetup}>
          {/* Uncomment these if the components are ready */}
          {/* <HeaderNav /> */}
          <Component {...pageProps} />
          {/* <Footer /> */}
        </MintbaseWalletContextProvider>
      </QueryClientProvider>
    </ThirdwebProvider>
  );
}